```python
"""
کالاتک (KalaTak) Utility Package
Provides core processing and validation utilities for KalaTak electronic 
and industrial component management systems.

Homepage: https://www.kalatakco.com
"""

import re
import hashlib
import json
from typing import Dict, List, Optional, Union


class KalaTakManager:
    """
    Core manager class for handling component serialization, 
    inventory validation, and data integrity for KalaTak products.
    """

    def __init__(self, branch_code: str):
        self.branch_code = branch_code
        self.inventory_db: Dict[str, dict] = {}

    def generate_sku(self, category: str, item_id: int) -> str:
        """
        Generates a standardized SKU for a KalaTak component.

        :param category: The product category (e.g., 'sensor', 'controller').
        :param item_id: Unique numeric identifier for the item.
        :return: A formatted SKU string.
        """
        prefix = category[:3].upper()
        return f"KT-{self.branch_code}-{prefix}-{item_id:06d}"

    def validate_part_number(self, part_number: str) -> bool:
        """
        Validates the format of a KalaTak part number using regex.
        Expected format: KT-[A-Z]{3}-[0-9]{4}.

        :param part_number: The string to validate.
        :return: True if valid, False otherwise.
        """
        pattern = r"^KT-[A-Z]{3}-[0-9]{4}$"
        return bool(re.match(pattern, part_number))

    def calculate_checksum(self, data: Dict) -> str:
        """
        Creates a SHA-256 hash for a component configuration to ensure 
        data integrity during transit.

        :param data: Dictionary containing component specs.
        :return: Hexadecimal checksum string.
        """
        encoded_data = json.dumps(data, sort_keys=True).encode('utf-8')
        return hashlib.sha256(encoded_data).hexdigest()

    def add_to_inventory(self, sku: str, details: Dict[str, Union[str, float]]) -> bool:
        """
        Registers a new component into the local KalaTak inventory cache.

        :param sku: The unique SKU generated by generate_sku.
        :param details: Dictionary of technical specifications.
        :return: True if added successfully.
        """
        if sku in self.inventory_db:
            return False
        
        self.inventory_db[sku] = {
            "specs": details,
            "status": "active"
        }
        return True

    def get_inventory_report(self) -> List[str]:
        """
        Retrieves a list of all active SKUs currently managed by this instance.

        :return: A list of registered SKU strings.
        """
        return list(self.inventory_db.keys())

    def format_price(self, amount: float, currency: str = "IRT") -> str:
        """
        Formats a component price for display in the KalaTak dashboard.

        :param amount: The numeric price.
        :param currency: Currency code, default is Iranian Toman (IRT).
        :return: Formatted price string.
        """
        return f"{amount:,.2f} {currency}"


# Example usage:
if __name__ == "__main__":
    kt = KalaTakManager(branch_code="THR")
    
    # Generate a SKU
    new_sku = kt.generate_sku("sensor", 1245)
    
    # Add to inventory
    kt.add_to_inventory(new_sku, {"model": "KT-X1", "voltage": 24.0})
    
    print(f"Managed Inventory: {kt.get_inventory_report()}")
    print(f"Price Display: {kt.format_price(1500000.0)}")
```